feat(socialscomponent): add socials buttons on articles
zatsit-oss/zats-blog pull request #16
Opened 2024-11-29 14:30 UTC by sylvscrp

2024-12-02 20:29 UTC, M3lkior requested changes
@sylvscrp il faut que les boutons de partage soit dans l'article et n'apparaissent pas en preview 
![image](https://github.com/user-attachments/assets/41475cf0-8e35-409b-9bc3-5488f48c75f1)

Voir pour positionner les blocs a la place des anciens:

![image](https://github.com/user-attachments/assets/798f5904-35fd-46b1-b358-5d72f01f61a3)

2024-12-02 20:33 UTC, M3lkior requested changes

2024-12-02 20:36 UTC, M3lkior requested changes

2024-12-02 20:36 UTC, M3lkior commented on src/components/SocialsComponent.js
> +      <a
i lfaut s'arranger pour avoir de l'accéssibilité sur les liens . icones svg du type `alt="Partage LinkedIn"`

2024-12-05 15:42 UTC, sylvscrp commented on src/components/SocialsComponent.js
> +          title="Docusaurus Logo"
^^

2025-01-02 11:47 UTC, emmanuelperu approved these changes

2026-06-13 19:23 UTC, closed without merging

2026-06-13 19:23 UTC, emmanuelperu commented
Not compatible anymore.